---
- name: Add user to rocky group server
  hosts: rocky8
  become: true
  become_user: root

  tasks:
    - name: Upgrade pip self-update
      ansible.builtin.pip:
        name: pip
        state: latest

    - name: Install ansible python package
      ansible.builtin.pip:
        name:
          - setuptools_rust
          - ansible
        extra_args: --upgrade

    - name: Execute install script
      ansible.builtin.script:
        cmd: command.py
        executable: /usr/bin/python3
      register: result
