---
- name: Galaxy Mysql
  hosts: rocky8
  become: true
  become_user: root
  gather_facts: false
  vars_files:
    - vault.yml

  collections:
    - jabdr.sql_query
  tasks:
    # - name: Install dependencies
    #   ansible.builtin.dnf:
    #     name:
    #       - python3-sqlalchemy
    # - name: Install python Mysql
    #   ansible.builtin.command: pip3 install pymysql
    #   changed_when: false
    # - name: Try to create database as root/nopassword first. If not allowed, pass the credentials
    #   community.mysql.mysql_db:
    #     login_user: "{{ login_user }}"
    #     login_password: "{{ login_password }}"
    #     name: 9prints_store_fog
    #     state: present
    #     login_host: "{{ login_host }}"
    # - name: Simple select query to acme db
    #   community.mysql.mysql_query:
    #     login_user: "{{ login_user }}"
    #     login_password: "{{ login_password }}"
    #     login_host: "{{ login_host }}"
    #     login_db: 9prints_store_fog
    #     query: DELETE FROM db_test

    - name: Copy database dump file
      ansible.builtin.copy:
        src: testdb.sql
        dest: /tmp
        mode: '0644'

    - name: >
        Import dump.sql,
        similar to mysql -u <username> -p <password> < dump.sql
      community.mysql.mysql_db:
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"
        name: 9prints_store_fog
        login_host: "{{ login_host }}"
        state: import
        target: /tmp/testdb.sql

    - name: Debug my vault
      ansible.builtin.debug:
        msg: "my login_host is {{ login_host }}"
