---
- name: Install docker
  hosts: rocky8
  become: true
  tasks:
    - name: Uninstall old versions
      ansible.builtin.dnf:
        name:
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent

    - name: Set up docker repository
      ansible.builtin.shell: |
        dnf install -y yum-utils
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      changed_when: false

    - name: Install the latest version of Docker Engine and containerd
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify: Start and enable docker

    - name: Add the current user to the docker group
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: true

  handlers:
    - name: Start and enable docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
